/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ignazio
 * Created: 26-lug-2016
 */

CREATE TABLE ObjectSale
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    descrizione VARCHAR(300),
    num_pezzi INTEGER,
    prezzo DOUBLE PRECISION,
    categoria VARCHAR(128),
    urlImmagine VARCHAR(128),
    idVendita INTEGER,
    FOREIGN KEY (idVendita) REFERENCES Venditore(id)
);