/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ignazio
 * Created: 26-lug-2016
 */

CREATE TABLE venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(32),
    conto DOUBLE
);